"""Export compact rules from independently captured native equipment pools."""
import json
from audit_generation_coverage import ROOT

def main():
 read=lambda name:json.loads((ROOT/name).read_text(encoding='utf8'))
 jewelry=read('normal-jewelry-pools-native.json');equipment=read('normal-equipment-pools-native.json')
 source=read('normal-affixes-native.json');complex=read('normal-complex-affixes-native.json');tables=[]
 for side in range(2):
  table={}
  for record in source[['prefix','suffix'][side]]:
   id=record['id'];stats=record['stats'];draws=record['draws']
   if side==0 and 521<=id<=540:
    group=521+(id-521)//5*5;key=stats['10'][0];chance=stats['11'][:3];levelkey={521:126,526:114,531:117,536:186}[group]
    lo=stats[str(levelkey)]-draws[-1][2]
    rule=dict(selector=[str(group),key],rows=[[key,0,0,True],[*chance,True],[levelkey,lo,lo+draws[-1][1],True]])
   elif side==1 and 418<=id<=422:
    lo=stats['206']-draws[-1][2]
    rule=dict(selector=['418',205],rows=[[205,0,0,True],[207,3,3,True],[206,lo,lo+draws[-1][1],True]])
   elif '11' in stats:
    rule=dict(rows=[[*stats[str(i)][:3],True] for i in (10,11)])
   else:
    key,lo,hi,tier=stats['10'];extra=side==0 and 426<=id<=430 or side==1 and id==544
    assert len(stats)==(3 if extra else 2),(side,id)
    rule=[key,lo,hi,bool(draws),*(['class'] if extra else [])]
   table[id]=rule
  tables.append(table)
 rules=dict(buildSha256=jewelry['buildSha256'],pools={**jewelry['rules'],**equipment['rules']},affixes=tables,procTables=complex['tables'])
 weapon=ROOT/'normal-weapon-pools-native.json'
 if weapon.exists():rules['weapon']=read(weapon.name)['rules']
 (ROOT.parent.parent/'engine/normal_affix_rules.js').write_text('// Current native normal equipment pools and prefix/suffix ranges. Generated by export_normal_affix_rules.py.\nexport const NORMAL_AFFIX_RULES = '+json.dumps(rules,separators=(',',':'))+';\n',encoding='utf8')
 for name,target in [('normal-affix-cases-0123468.json','current_equipment_affixes_native.json'),('normal-equipment-modifiers-native.json','current_equipment_modifiers_native.json'),('normal-complex-affixes-native.json','current_complex_affixes_native.json')]:
  data=read(name);data['buildSha256']=rules['buildSha256'];(ROOT.parent.parent/'tests'/target).write_text(json.dumps(data,separators=(',',':'))+'\n',encoding='utf8')
 print('Exported',sum(map(len,tables)),'affixes for types',list(rules['pools']),flush=True)

if __name__=='__main__':main()
