"""Extract current-build tables from bounded, named native decompilations.

This deliberately fails on unrecognized cases instead of guessing a stat rule.
The executable is read only; output is simulator data, never game data.
"""
import hashlib
import json
import re
import struct
from pathlib import Path
import pefile

ROOT = Path(__file__).resolve().parent

def assignments(text):
    return {int(a, 16): int(v, 0) for a, v in re.findall(r'_DAT_([0-9a-f]+) = (0x[0-9a-f]+|\d+);', text)}

def switch_keys(name):
    text = (ROOT / f'{name}.c').read_text()
    address = int(re.search(r'&DAT_([0-9a-f]+) \+ \(longlong\)\(int\)uVar\d+ \* 0x14', text)[1], 16)
    values = assignments(text)
    result = []
    while address in values and values.get(address + 12) == 10:
        result.append(values[address])
        address += 20
    assert result, name
    return result

def decode_double(value):
    return struct.unpack('<d', struct.pack('<Q', int(value, 0)))[0]

def extract():
    source = ROOT / 'HeroSiegeC6E.exe'
    sha = hashlib.sha256(source.read_bytes()).hexdigest()
    assert sha == 'c6ecc069cfc02e105c988d48f9469f4e2e6260ad44c41dab8001f2612b8b3db4'
    text = (ROOT / 'GetStatUpgrades.c').read_text()
    keys = switch_keys('GetStatUpgrades')
    blocks = re.split(r'\n  case (0x[0-9a-f]+|\d+):\n', text)
    upgrades = {}
    for label, block in zip(blocks[1::2], blocks[2::2]):
        key = keys[int(label, 0)]
        direct = re.search(r'uStack_d78 = (0x[0-9a-f]+|\d+);', block)
        integer = re.search(r'FUN_140189960\(&uStack_d78,(0x[0-9a-f]+|\d+)\);', block)
        real = re.search(r'FUN_14018c000\(&uStack_d78,(0x[0-9a-f]+|\d+)\);', block)
        assert sum(x is not None for x in (direct, integer, real)) == 1, (label, block)
        amount = int(integer[1], 0) if integer else decode_double((direct or real)[1])
        flag = re.search(r'func_0x00014018bf90\([^,]+,([01])\)', block)
        if flag:
            additive = flag[1] == '1'
        else:
            flag = re.search(r'uStack_d58 = (0x[0-9a-f]+|\d+);', block)
            if flag is None:
                copied = re.search(r'FUN_1401898c0\(&uStack_d68,&(uStack_\w+)\);', block)
                assert copied, (label, block)
                flag = re.search(rf'{copied[1]} = (0x[0-9a-f]+|\d+);', block)
            assert flag, (label, block)
            additive = decode_double(flag[1]) == 1
            assert decode_double(flag[1]) in (0, 1)
        upgrades[key] = {'amount': amount, 'additive': additive}
    assert len(upgrades) == len(keys) == 181
    pe = pefile.PE(str(source), fast_load=True)
    # DefineGlobals: zpm1 <- double at RIP 0x140919803 + 0xE8BCEF5.
    percent = struct.unpack('<d', pe.get_data(0x919803 + 0xe8bcef5, 8))[0]
    assert percent == 0.01, percent
    return {
        'schema': 1, 'buildSha256': sha,
        'source': 'Current native executable, bounded decompilation and x86-64 arithmetic inspection',
        'starPercentUnit': percent,
        'tierMultipliers': [2, 1.75, 1.5, 1.25, 1, 1, 1],
        'corruptionMultiplier': 0.25,
        'corruptionExempt': switch_keys('GetDisabledAttributesBrick'),
        'upgradeExempt': switch_keys('GetDisabledAttributes'),
        'nonNumericStats': switch_keys('DontRandomStats'),
        'upgradeDisabledSkills': switch_keys('GetDisabledUpgradeStats'),
        'upgrades': upgrades,
    }

if __name__ == '__main__':
    result = extract()
    target = ROOT.parent.parent / 'data' / 'current_modifier_rules.json'
    target.write_text(json.dumps(result, indent=2) + '\n')
    module = ROOT.parent.parent / 'engine' / 'modifier_rules.js'
    module.write_text('// Generated by research/current/extract_modifier_rules.py.\n'
                      '// Native build and extraction evidence are recorded in research/current.\n'
                      + 'export const MODIFIER_RULES = ' + json.dumps(result, separators=(',', ':')) + ';\n')
    print(f'{len(result["upgrades"])} star rules; {len(result["corruptionExempt"])} corruption exceptions; {target}')
