// Generated by tools/build_socket_restrictions.py. Do not edit.
// Native normal-consumable info50 -> CreateItemNew -> Add Sockets gate.
// Source SHA256 c6ecc069cfc02e105c988d48f9469f4e2e6260ad44c41dab8001f2612b8b3db4
export const SOCKET_RESTRICTED_CONSUMABLES = Object.freeze([12, 14, 15, 16, 17, 24, 25]);
