import assert from 'node:assert/strict';
import fs from 'node:fs';
import { Sim } from '../engine/index.js';
import { recipeContext } from '../engine/recipe_context.js';
import { recipeCardHtml } from '../ui/recipe-card.js';
import { validateCraft } from '../engine/validation.js';
const read=n=>JSON.parse(fs.readFileSync(new URL('../data/'+n,import.meta.url),'utf8'));
const sim=new Sim({recipes:read('recipes.json'),catalog:read('items_catalog.json'),statNames:read('stat_names.json'),pools:read('stat_pools.json'),profiles:read('item_profiles.json')});
const r=mechanic=>sim.recipes.find(x=>x.mechanic===mechanic);
const stack=(item,amount=1)=>({item,amount});
const row=sim.catalog.rows.find(x=>x.kind==='unique'&&x.cls===3);
const weapon=(def={})=>sim.makeItem(row.cls,row.b,{a:123456,c:1,j:row.sub,...def},{row,isUnique:true,tier:5});
const crystal=stack(sim.makeItem(14,58),1);
const codex=sim.makeItem(11,23,{a:123456}),singleCodex=sim.makeItem(11,23,{a:98765});
const codexStack=stack(codex,2);
assert.equal(recipeContext(r('upgrade_codex'),[codexStack]).dimmed,true,'multi-Codex stacks cannot be modified');
const upgrade=r('upgrade_codex'),upgradeMaterials=upgrade.ingredients.filter(i=>i.itemId!=null).map(i=>stack(sim.makeItem(i.itemType,i.itemId),i.amount));
assert.match(validateCraft(upgrade,[codexStack,...upgradeMaterials]).reason,/one at a time/);
assert.equal(validateCraft(upgrade,[codexStack,stack(singleCodex),...upgradeMaterials]).target,singleCodex,'skip the multi-item stack and use the single Codex');
assert.equal(recipeContext(r('satanic_crystal'),[]).dimmed,false);
assert.equal(recipeContext(r('satanic_crystal'),[stack(weapon())]).rank,1,'equipment is compatible before materials are added');
assert.equal(recipeContext(r('satanic_crystal'),[stack(weapon()),crystal]).rank,0,'ingredients make the recipe ready');
assert.equal(recipeContext(r('random_orbs'),[stack(weapon())]).dimmed,true,'unrelated Tarot recipe is dim');
assert.equal(recipeContext(r('satanic_crystal'),[stack(weapon({r:1})),crystal]).dimmed,true,'corrupted equipment cannot use Crystal');
const clean=weapon(),mixed=[stack(weapon({r:1})),stack(clean),crystal];
assert.equal(validateCraft(r('satanic_crystal'),mixed).target,clean,'skip the first invalid item and craft the eligible one');
assert.equal(recipeContext(r('satanic_crystal'),mixed).rank,0);
assert.equal(recipeContext(r('cleanse_prophet'),[stack(weapon({r:1}))]).rank,1,'cleansing is relevant to corrupted equipment');
assert.equal(recipeContext(r('cleanse_prophet'),[stack(weapon())]).dimmed,true);
assert.equal(recipeContext(r('satanic_crystal'),[crystal]).dimmed,true,'a reagent alone must not advertise an absent target');
const fragment=sim.recipes.find(x=>x.mechanic==='create'&&x.ingredients.length===1&&/Gypsy.*Fragment/i.test(x.ingredients[0].name));
const fragmentStack=stack(sim.makeItem(fragment.ingredients[0].itemType,fragment.ingredients[0].itemId),1);
assert.equal(recipeContext(fragment,[fragmentStack]).rank,1,'partial fragment stacks surface their merge');
fragmentStack.amount=fragment.ingredients[0].amount;
assert.equal(recipeContext(fragment,[fragmentStack]).rank,0);
assert.equal(recipeContext(r('random_dungeon_keys'),[stack(weapon())]).ready,false);
const dimmed=recipeCardHtml(r('random_orbs'),{context:recipeContext(r('random_orbs'),[stack(weapon())])});
assert.match(dimmed,/dimmed/);assert.doesNotMatch(dimmed,/<button[^>]*\sdisabled(?:\s|>)/,'unrelated recipes remain inspectable');
for(const recipe of sim.recipes)for(const contents of [[],[stack(weapon())],[stack(weapon({r:1}))],[fragmentStack]])assert.doesNotThrow(()=>recipeCardHtml(recipe,{context:recipeContext(recipe,contents)}));
console.log('PASS Cube relevance: missing materials, ready crafts, corruption, unrelated recipes, fragment merges, empty Cube and all recipe tiles.');
