"""Publish the item restriction only from complete native metadata/copy captures."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BUILD = 'c6ecc069cfc02e105c988d48f9469f4e2e6260ad44c41dab8001f2612b8b3db4'


def main():
    definitions = json.loads((ROOT/'research/current/consumable-restrictions-native.json').read_text(encoding='utf8'))
    chains = json.loads((ROOT/'tests/current_consumable_socket_native.json').read_text(encoding='utf8'))
    assert definitions['buildSha256'] == chains['buildSha256'] == BUILD
    assert sorted(row['b'] for row in definitions['rows']) == list(range(27))
    assert len(chains['fixtures']) == 81
    blocked = []
    for row in sorted(definitions['rows'], key=lambda row: row['b']):
        assert not row['deferred']
        base = {int(k): v for name, (k, v) in row['calls'] if name in ('itemBaseInfoStruct', 'SetBaseItemInfo')}
        present, value = 50 in base, base.get(50)
        assert not present or value == 1, ('Unexpected restriction value', row['b'], value)
        cases = [f for f in chains['fixtures'] if f['b'] == row['b']]
        assert sorted(f['seed'] for f in cases) == [1, 123456, 999999937]
        for f in cases:
            assert f['basePresent'] == f['itemPresent'] == present
            assert f['baseValue'] == f['itemValue'] == value
            assert f['resolved'] == (1 if present else -1)
            assert f['gateAllowed'] == (not present)
        if present:
            blocked.append(row['b'])
    output = '// Generated by tools/build_socket_restrictions.py. Do not edit.\n'
    output += '// Native normal-consumable info50 -> CreateItemNew -> Add Sockets gate.\n'
    output += '// Source SHA256 '+BUILD+'\n'
    output += 'export const SOCKET_RESTRICTED_CONSUMABLES = Object.freeze('+json.dumps(blocked)+');\n'
    (ROOT/'engine/socket_restriction_rules.js').write_text(output, encoding='utf8', newline='\n')
    print('Published', len(blocked), 'restricted normal consumables from 27 definitions and 81 native chains.')


if __name__ == '__main__':
    main()
