"""Publish reviewed current-game craft constants, with native source provenance."""
import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
keys=json.loads((root/'research/current/dungeon-keys-native.json').read_text())
relics=[(7,0,50),(10,0,88),(10,0,86),(10,0,85),(10,0,87),(3,10,12),(7,0,53),(7,0,54),(7,0,55)]
catalog=json.loads((root/'data/items_catalog.json').read_text(encoding='utf8'))
rows=[]
for cls,sub,b in relics:
    row=next(r for r in catalog if r['cls']==cls and r.get('sub',0)==sub and r['b']==b and r['kind']=='unique')
    rows.append(dict(itemType=cls,subtype=sub,itemId=b,name=row['name']))
assert all(any(r['cls']==12 and r['b']==b and r['kind']=='normal' for r in catalog) for b in keys)
native=json.loads((root/'research/current/equipment-definitions-native.json').read_text())
weapons=['Sword','Dagger','Mace','Axe','Claw','Polearm','Chainsaw','Staff','Cane','Wand','Book','Spellblade','Bow','Gun','Flask','Throwing','Universal']
types={'Helmets':0,'Chests':1,'Boots':2,'Gloves':4,'Amulets':5,'Shields':6,'Rings':7,'Belts':8,'Charms':10,'Flask':18}
excluded=[];metadata={}
for routine,definition in native.items():
    if not routine.startswith('gml_Script_DefineItemUnique'):continue
    suffix=routine.removeprefix('gml_Script_DefineItemUnique')
    if suffix.startswith('Weapons') and suffix[7:] in weapons:cls,sub=3,weapons.index(suffix[7:])+1
    elif suffix in types:cls,sub=types[suffix],0
    else:continue
    for row in definition['rows']:
        info={int(args[0]):args[1] for name,args in row['calls'] if name in ('SetBaseItemInfo','itemBaseInfoStruct')}
        key=f'{cls}:{sub}:{row["b"]}'
        metadata[key]=info
        if info.get(40):excluded.append(key)
loot=json.loads((root/'research/current/unique-loot-lists-native.json').read_text())
assert list(map(len,loot))==[50,61,79,152,221,380]
craft_pools=[[],[],[],[],[],[]];angelic=[];unholy=[]
for tier,entries in enumerate(loot):
    for raw_entry in entries:
        cls,sub,b=map(int,raw_entry)
        info=metadata[f'{cls}:{sub}:{b}'];rarity=int(info.get(27,6))
        assert info[32]==tier
        if info.get(40):continue
        entry=[cls,sub,b]
        if rarity not in (7,10):craft_pools[tier].append(entry)
        elif tier==5:(angelic if rarity==7 else unholy).append(entry)
assert list(map(len,craft_pools))==[48,61,79,152,218,203]
assert len(angelic)==31 and len(unholy)==17
rules={'buildSha256':'c6ecc069cfc02e105c988d48f9469f4e2e6260ad44c41dab8001f2612b8b3db4',
       'dungeonKeys':keys,'relicUniques':rows,'maximumCodexTier':20,
       'uniqueCraftExcluded':sorted(excluded),'randomUniqueExcludedRarities':[7,10],
       'uniqueCraftByTier':craft_pools,'angelicCraft':angelic,'unholyCraft':unholy,
       'source':'DoCraftResult cases 4, 14–18, 20, 30; native GetDungeonKeys(false); Controller Unique loot construction, current BaseItemInfo(40/41) exclusions and tier selection.'}
(root/'data/current_craft_rules.json').write_text(json.dumps(rules,indent=2)+'\n',encoding='utf8',newline='\n')
(root/'engine/craft_rules.js').write_text('// Generated by tools/build_current_craft_rules.py.\nexport const CRAFT_RULES = '+json.dumps(rules,separators=(',',':'))+';\n',encoding='utf8',newline='\n')
print('Verified',len(keys),'Dungeon Keys and',len(rows),'Relic uniques against the catalog.')
print('Published',len(excluded),'explicit current-game Unique craft exclusions.')
